import { isValidUuid } from "../../../auth/organization.js";
import type { CreateAssessmentEventInput, CreateAssessmentPortionInput, CreateAssessmentSchemeComponentInput, CreateAssessmentSchemeInput } from "./types.js";

export class AssessmentValidationError extends Error { code = "VALIDATION_ERROR"; }
const uuid = (value: string | null | undefined, field: string) => { if (!value || !isValidUuid(value)) throw new AssessmentValidationError(`${field} is invalid.`); return value.trim(); };
const text = (value: string | null | undefined, field: string) => { const result = value?.trim(); if (!result) throw new AssessmentValidationError(`${field} is required.`); return result; };
export const validateScheme = (input: CreateAssessmentSchemeInput) => { uuid(input.boardId, "Board id"); if (input.academicYearId) uuid(input.academicYearId, "Academic year id"); text(input.schemeCode, "Scheme code"); text(input.name, "Scheme name"); text(input.version, "Scheme version"); };
export const validateComponent = (input: CreateAssessmentSchemeComponentInput) => { uuid(input.schemeId, "Scheme id"); uuid(input.assessmentTypeId, "Assessment type id"); text(input.code, "Component code"); text(input.name, "Component name"); if (input.maximumMarks !== undefined && input.maximumMarks !== null && input.maximumMarks < 0) throw new AssessmentValidationError("Maximum marks cannot be negative."); if (input.weightage !== undefined && input.weightage !== null && input.weightage < 0) throw new AssessmentValidationError("Weightage cannot be negative."); if (input.durationMinutes !== undefined && input.durationMinutes !== null && input.durationMinutes < 0) throw new AssessmentValidationError("Duration cannot be negative."); };
export const validateEvent = (input: CreateAssessmentEventInput) => { if (input.organizationId) uuid(input.organizationId, "Organization id"); uuid(input.academicYearId, "Academic year id"); uuid(input.classId, "Class id"); if (input.subjectId) uuid(input.subjectId, "Subject id"); if (input.calendarId) uuid(input.calendarId, "Calendar id"); if (input.calendarPeriodId) uuid(input.calendarPeriodId, "Calendar period id"); if (input.assessmentSchemeVersionId) uuid(input.assessmentSchemeVersionId, "Assessment scheme id"); if (input.assessmentTypeId) uuid(input.assessmentTypeId, "Assessment type id"); text(input.title, "Assessment title"); const start = new Date(input.scheduledStart); const end = new Date(input.scheduledEnd); if (Number.isNaN(start.valueOf()) || Number.isNaN(end.valueOf()) || end < start) throw new AssessmentValidationError("Assessment schedule is invalid."); };
export const validatePortion = (input: CreateAssessmentPortionInput) => { uuid(input.assessmentEventId, "Assessment event id"); uuid(input.curriculumStructureId, "Curriculum structure id"); if (input.curriculumNodeId) uuid(input.curriculumNodeId, "Curriculum node id"); text(input.sourceType ?? "BOARD_CURRICULUM", "Source type"); };
export { uuid, text };
